### ISSUE TITLE
STATUS_ACCESS_VIOLATION with Evaluate function while parsing xpath [Urgent]

### ISSUE THREAD

**Issue by mayankjoshii** [KWARC/rust-libxml#105]
I'm trying to implement the code to parse the Xpath, but the issue I'm facing is when I'm returning  the variable of type `evaluate(&self, xpath: &str) -> Result<Object, ()>` from the funtion, my application is crashing. 

```
fn parse_xpath(test_val: &str) -> Object{

   let parser = Parser::default();
    let doc = parser.parse_file("file1.xml").unwrap();
    let xpath_c = Context::new(&doc).unwrap();
    let  xpath_res = xpath_c.evaluate(test_val).unwrap();

    xpath_res
}

fn main() {

    let xpath_res = parse_xpath("//Root/Os/Win");

    let node_cnt = xpath_res.get_number_of_nodes();
    println!("{} nodes are present", node_cnt);
    
    for node in &xpath_res.get_nodes_as_vec(){
            println!("Found: {}", node.get_name());                                  //program crashing after reaching here.
            println!("Found: {:?}", node.get_attributes());
            println!("Found: {:?}", node.get_child_elements());
    }

}
```

I want to know the way I'm returning the Object of type evaluate correctly or what is the correct way to do that?

Program output: 

```
2 nodes are present
Found: Plugin
error: process didn't exit successfully: target\debug\SampleProgram.exe (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

**Comment by dginev** [comment]
Hi @mayankjoshii ,

Indeed, it looks like the `node.get_attributes()` call raised caused the Rust panic.

Could you share the XML file - ideally a minimal version of it - which has the problem?

You are using `Object` correctly, and you seem to be getting a two element vector successfully as the result of the xpath evaluation.

I am guessing there is an unhandled case of memory management in the wrapper's implementation of `get_attributes`, but it would really help to have a piece of XML we can test against.

**Comment by mayankjoshii** [comment]
Hi @dginev,

The issue is sometimes repro with this statement itself also: `let node = &xpath_res.get_nodes_as_vec();` 

The sample XML file is: 

```
<Root SchemaVersion="1.5">
	<Test>
		<Test1>win</Test1>
	</Test>
	<Os>
		<Win type="0" description="test" >
			<Startfile>BIOS</Startfile>
			<CliToStdout>
				<Command>ExecBIOS.exe</Command>
			</CliToStdout>
		</Win>
	</Os>
</Root>
```

**Comment by dginev** [comment]
@mayankjoshii sorry this took so long for me to follow-up on again, but maybe at this point you have caught the tricky issue in your code.

I think the wrapper is working as expected here, but it is not "as safe as Rust", since we are not using lifetimes to guard against this type of problem.

Namely, when your example initializes the libxml Document within a helper function -`parse_xpath()` above - at the end of that function call ownership of that document will be released, and its memory will be Drop-ed. So when you evaluate an xpath against it, there will be nothing left at the position the XPath context is pointing to.

We could enforce better ownership here for sure, but the simple fix is to make sure the document object outlives the xpaths using it - either by initializing it in the main function, or by returning it from the helper, alongside the XPath.

I'll close here, but PRs with various experimentation on this theme are welcome - and we may reorganize to a better ownership model in the Rust layer.
