### ISSUE TITLE
XML with BOM not parsed

### ISSUE THREAD

**Issue by Gedweb** [KWARC/rust-libxml#33]
I found trouble with some files, inside containing BOM.
It's just not parsed as a XML with `parse_file` method.

**Comment by dginev** [comment]
Hi @Gedweb  - I am not personally familiar with BOM, and the wrapper currently only supports unicode documents - it's quite basic in that regard for now.

If you could point me to some libxml examples of working with BOM, that would help a lot. And you're even better off if you file a pull request with a fix that supports your workflow - we are quite good with merging enhancements in quickly and releasing new minor versions of the library.

Thanks for reporting the issue!

**Comment by Gedweb** [comment]
The UTF-8 BOM just allows the reader to identify a file as being encoded in UTF-8.
After reading we can drop this bytes. I'll prepare pull request.

**Comment by Gedweb** [comment]
So, inside libxml2 able `xmlSwitchEncoding` function, but I not so familiar in C.

**Comment by dginev** [comment]
Hi @Gedweb ,

I took a second look - and I would need a minimal example of what you are trying to parse, and the Rust code you wrote to parse it and what you would expect to be different. As I mentioned earlier, just not that familiar with the BOM details.

The code you linked to in libxml should be executed exactly as you see it there, as the current wrapper doesn't set any encoding for the parser context internally.

**Comment by Alexhuszagh** [comment]
I'm tagging myself to create an example shortly.

**Comment by dginev** [comment]
I'm back to this issue, @Alexhuszagh , @Gedweb , just linking/attaching a standalone XML file and explaining the failure to parse will be a huge help for me to jump in and try to improve the wrapper.

**Comment by Gedweb** [comment]
@dginev, look, first 3 bytes is the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark).
BOM is not same for a different UTF encoding. When you found that magic octets in a start of file, just drop it. 
FYI, inside libxml2 you can found ready solutions. 
[cache.zip](https://github.com/KWARC/rust-libxml/files/3080919/cache.zip)
![image](https://user-images.githubusercontent.com/6544152/56145816-ad1f4780-5fad-11e9-86b2-4137c7c89eed.png)
In textual mode no one editor not show you that signs, only binary.

**Comment by Alexhuszagh** [comment]
@dginev Here's a very simple example. The entire example can be auto-generated with the following (Python) code, which takes an existing BOM-less XML file in UTF-8 encoding and prepends a UTF-8 BOM (0xEF 0xBB 0xBF) to the byte stream.

```python
import codecs
import requests

response = requests.get('https://www.uniprot.org/uniprot/P46406.xml')
response.raise_for_status()
with open('without_utf8bom.xml', 'wb') as f:
    f.write(response.content)
with open('with_utf8bom.xml', 'wb') as f:
    f.write(codecs.BOM_UTF8 + response.content)
```

Now, here's the simple Rust project that recreates the example:

**Cargo.toml**
```toml
[package]
name = "libxmltest"
version = "0.1.0"

[dependencies]
libxml = "0.2"
```

**src/main.rs**
```rust
extern crate libxml;
use libxml::parser::Parser;


fn parse_file(path: &str) {
    let parser = Parser::default();
    let doc = parser.parse_file(path).expect(path);
    doc.get_root_element().expect(path);
}

fn main() {
    parse_file("/path/to/without_utf8bom.xml");
    parse_file("/path/to/with_utf8bom.xml");

    println!("Hello, world!");
}
```

Running the generated binary produces:

```bash
thread 'main' panicked at '/path/to/with_utf8bom.xml', src/libcore/option.rs:1008:5
note: Run with `RUST_BACKTRACE=1` for a backtrace
```

**Comment by Alexhuszagh** [comment]
In case you don't want to run the script, here is a ZIP file containing both the BOM-less and the BOM-containing XML files.

[bom.zip](https://github.com/KWARC/rust-libxml/files/3080966/bom.zip)

**Comment by dginev** [comment]
Fantastic, thanks for all the details! Taking a look...

**Comment by Alexhuszagh** [comment]
@dginev I believe I can actually supply a PR to fix this issue, since the offending source code is here:
https://github.com/KWARC/rust-libxml/blob/master/src/parser.rs#L94

There are two issues here:
1. (Unrelated to the aforementioned issue) On Windows, you should likely as a UTF-16 path, rather than UTF-8, since UTF-8 paths are only valid on UNIX-like systems (and not Windows). Using `std::path::Path` and `as_os_str` will allow this code to be cross-platform. See [here](https://doc.rust-lang.org/std/ffi/struct.OsStr.html).
2. Manually-provided encoding. You should provide a `NULL` for the encoding, and then libxml will auto-detect the encoding unless it is explicitly provided, allowing it to detect the correct BOM. If the encoding is provided, from what I remember, libxml2 will not accept any BOMs.

**Comment by dginev** [comment]
@Alexhuszagh both points sound like great improvements, and I will be very happy to accept a PR! Your bom files make very natural test cases as well.

I vividly recall writing the parser code as a first stab for my use, ignoring all complexity, so definitely time to improve on that.

**Comment by dginev** [comment]
Hi @Alexhuszagh , sorry to bump here again, but do you still plan to work on a PR? Let me know if I should try to patch this myself, since I'd like to get this issue closed. I'd be very happy to get a PR contributed since you have spent a lot more energy into studying the issue.

**Comment by Alexhuszagh** [comment]
Sorry, I'm working on it. I got a new contract position and then had a lot of personal issues in the meantime (depression is a royal PITA). I'm finishing the PR right now.

**Comment by Alexhuszagh** [comment]
@dginev @Gedweb This should be fixed in the following commit. Please review the changes prior to me submitting a PR:
https://github.com/Alexhuszagh/rust-libxml/commit/22707b893aa0bf0bbb200b384150fb95076cc941

The major differences are as follows:

1. Remove the encoding parameter, set it to `ptr::null()`, so the BOM may be read.
2. Since libxml2 does not support non-UTF8 file paths, but does allow arbitrary file streams and callbacks, use `xmlReadIO` and `htmlReadIO` rather than `xmlReadFile` and `htmlReadFile`, respectively.

Using xmlReadIO and htmlReadIO requires 3 steps:
1. The creation of a Rust `File` as raw, unowned void [pointer](https://github.com/Alexhuszagh/rust-libxml/blob/22707b893aa0bf0bbb200b384150fb95076cc941/src/parser.rs#L41).
2. A read callback that takes a `void*` context, a `char*` buffer, and an `int` length and converts this to a `Read::read` call on an unowned `File` [reference](https://github.com/Alexhuszagh/rust-libxml/blob/22707b893aa0bf0bbb200b384150fb95076cc941/src/parser.rs#L47).
3. A close callback that takes a `void*` context and converts this unowned, raw pointer to a boxed value and drops this owned box, ensuring no memory leaks and file [closure](https://github.com/Alexhuszagh/rust-libxml/blob/22707b893aa0bf0bbb200b384150fb95076cc941/src/parser.rs#L69).

Finally, we need to handle if the file is unable to be opened on Rust's end (adding a new error code), and we're good to go.

Thoughts? I've added a test case with `file01.xml` with a UTF8 BOM prepended to the file, and everything works as desired.

**Comment by Alexhuszagh** [comment]
Long term, we may want to allow the user to provide a manual encoding, if there is no BOM, if desired, if not, let libxml2 auto-detect the encoding (which with BOMs, charset declarations, and character set detection is very robust).

In short, we'd need another function in addition to `parse_file`, `parse_file_with_encoding(filename: &str, encoding: Option<&str>)`. `parse_file` would call `parse_file_with_encoding` with `None` for the encoding, and we would use `ptr::null()` if no encoding is provided, otherwise, we would use the CString representation of `&str`. This way, we could provide the full functionality of libxml2 from a high-level perspective.

**Comment by Alexhuszagh** [comment]
@Gedweb @dginev I've updated the commit to separate the fixes into two commits: one to add support for BOMs and non-UTF8 [encodings](https://github.com/Alexhuszagh/rust-libxml/commit/9c3cf663452643aa7643201e9fa7dc23bc9bf0b8) and one to add support for Unicode [paths](https://github.com/Alexhuszagh/rust-libxml/commit/728aaee64db531af725dae7880dbee8802c51a1c) (with the 🔥 emoji in the path, testing support for Unicode and non-BMP characters).

A few issues with the commits before:
1. I didn't implement `parse_string` and `is_well_formed_html` to accept BOMs.
2. I didn't allow user-specified encodings if desired.

To remedy this, I updated `parse_file`, `parse_string`, and `is_well_formed_html` to add `with_encoding` to each, and implemented each one to call the `with_encoding` internally. In addition, `parse_string` and `is_well_formed_html` accept `AsRef<[u8]>`, which allows them to accept non-UTF8 data, but still accept `&str` (which is implicitly converted to `AsRef<[u8]>`). This allows backwards compatibility, but also work with our broadened assumptions. Finally, I've unittests for UTF-8, UTF-16LE, UTF-16BE data with and without BOMs, and added unittests for paths with Unicode data (to ensure it works on Windows which uses UTF-16 paths).

Any comments? Or should I submit a PR?

**Comment by dginev** [comment]
Thanks for for the PR @Alexhuszagh ! I'm currently on holiday, but will be able to take a quick look and send any feedback / merge. I very much appreciate the fully self-contained contribution, thanks to everyone involved so far!

**Comment by dginev** [comment]
Alright, got to read through the approach you took, and while I'd clean up the code a little (e.g. by importing all used modules and simplifying the type annotations), I think the general setup is solid.

Rerunning my benchmark test shows no noticeable slowdown, which is neat, so I'll likely go ahead and merge the PR as-is.

**Comment by dginev** [comment]
#33 is now merged, thanks again @Alexhuszagh !

**Comment by Alexhuszagh** [comment]
@dginev Let me know if there are any suggestions for me to clean up the code (I tried to use your coding style for the commit for visual consistency, but obviously, I'm not an expert at that). I'd like for this to be easy to maintain, so I'd be glad to make minor changes to that effect.
