### ISSUE TITLE
Creating new documents from retrieved nodes

### ISSUE THREAD

**Issue by odra** [KWARC/rust-libxml#65]
Hello,

I am trying to create a new document from the results of `get_nodes_as_vec` and creating a new struct that contains a document but I get a memory error since `documet.set_root_element` uses a reference which is gone by the time the  get_nodes_as_vec`  loop is over (that's what I think is happening at least).

This is the code that generates the error:

```rust
extern crate libxml;

const XML: &str = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <notes>
    <note>
      <to>Tove</to>
      <from>Jani</from>
      <heading>Reminder</heading>
      <body>Don't forget me this weekend!</body>
    </note>
    </notes>";

#[derive(Clone)]
struct Node {
  xml_doc: libxml::tree::Document
}

impl Node {
  pub fn new(data: &str) -> Node {
    let parser = libxml::parser::Parser::default();
    let document = parser.parse_string(data.as_bytes()).unwrap();
    Node { xml_doc: document.clone() }
  }

  pub fn find_nodes(&self, query: &str) -> Vec<Node>  {
    let ctx = libxml::xpath::Context::new(&self.xml_doc).unwrap();
    let result = ctx.evaluate(query).unwrap();
    let mut v: Vec<Node> = Vec::new();

    for node in result.get_nodes_as_vec() {
      let mut doc = libxml::tree::Document::new().unwrap();
      doc.set_root_element(&node);
      v.push(Node{ xml_doc: doc.clone() });
    }
    v
  }
}

fn main() {
  let xml_node = Node::new(XML);
  let nodes = xml_node.find_nodes("//note");
}
```

This is the error I get when running it:

```
free(): invalid pointer
error: process didn't exit successfully: `/home/lrossetti/Work/sumatraproject/rumatra/target/debug/deps/rumatra-f41b8ad71503704e` (signal: 6, SIGABRT: process abort signal)
```

Is there another way to create a new document that contains a node? Should I directly use the libxml bindings?

**Comment by dginev** [comment]
Hi @odra , thanks for the report! The main problem from what I see in your code is that you're trying to wrestle down libxml2's way of dealing with nodes, but coming from a very intuitive high-level angle. This wrapper crate is (at the moment) staying quite close to the low-level requirements of libxml2, so you'd need to be somewhat compliant to that. In libxml2's approach, as best as I understand it, to move a node from one document to another you need a sequence of unbind-import steps, at which point you could invoke methods on the imported node in the target document. I rewrote your example to a minimal working version:

```rust
extern crate libxml;

const XML: &str = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <notes>
    <note>
      <to>Tove</to>
      <from>Jani</from>
      <heading>Reminder</heading>
      <body>Don't forget me this weekend!</body>
    </note>
    </notes>";

fn main() {
  let parser = libxml::parser::Parser::default();
  let source_doc = parser.parse_string(XML.as_bytes()).unwrap();
  let ctx = libxml::xpath::Context::new(&source_doc).unwrap();
  let result = ctx.evaluate("//note").unwrap();

  let mut targets = Vec::new();

  for mut node in result.get_nodes_as_vec() {
    let mut target_doc = libxml::tree::Document::new().unwrap();
    node.unlink();
    let imported_node = target_doc.import_node(&mut node).unwrap();
    target_doc.set_root_element(&imported_node);
    targets.push(target_doc);
  }
  println!("collected {:?} target documents", targets.len());
}
```

Crucially, if you use the argument `node` rather than the transplanted `imported_node`, you'll see the corruption of double-freeing the node.

Also importantly - no place in your code snippet actually required a `.clone()` call, so you may be able to simplify.

Let me know of what your most intuitive API would be here, maybe we can start a new submodule with higher-level functions that take the pain away. Something like `node.transfer_to(&target_document)` which automatically unbinds and imports the node, with all details hidden away.

**Comment by odra** [comment]
Thanks for the answer, that does makes total sense :)

I was struggling with it since I am not familiar with the libxml2 API itself but I think the rust API looks intuitive enough as it is.

I think an example file on how to do it would be good enough to help people who are not familiar with libxml2 (I can send a pr with it if you want to)!

**Comment by dginev** [comment]
Thanks for the offer, maybe a PR where your use cases is framed as a test would be nice - taking one of the example XML files we have in the repo and transferring them into a new document. We may even have the methods in the tests already, but they can be reorganized so that we have one file per conceptual example... If you feel upto doing some improvements there - you're most welcome to!

**Comment by dginev** [comment]
Closing here for now, but whenever you feel like sending a PR over, I'll happily review!
